name: npm-test
displayName: 'npm-test'
triggers:                                 # 流水线触发器配置
  push:                                   # 设置 master 分支 在产生代码 push 时精确触发（PRECISE）构建
    - matchType: PRECISE
      branch: master
commitMessage: ''                         # 通过匹配当前提交的 CommitMessage 决定是否执行流水线
stages:                                   # 构建阶段配置
  - stage:                                # 定义一个 ID 标识为 npm-build-stage ,名为 “npm Stage” 的阶段
      name: npm-build-stage
      displayName: 'npm Stage'
      failFast: false                     # 允许快速失败，即当 Stage 中有任务失败时，直接结束整个 Stage
      steps:                              # 构建步骤配置
        - step: npm-test@1                # 采用 npm 编译环境
          name: npm-test                 # 定义一个 ID 标识为 npm-build ,名为 “npm Step” 的阶段
          displayName: 'npm test'
          inputs:                         # 构建输入参数设定
            nodeVersion: 14             # 指定 node 环境版本为 10.1
            goals: "npm install && npm run test"